eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/

---
spring:
  data:
    mongodb:
      uri: mongodb://localhost:47017/test

---
---
# spring:
#   datasource:
#      hikari:
#       jdbc-url: jdbc:h2:~/testdb
    
   
#   jpa:
#    show-sql: true


---
spring:
  zipkin:
    base-url: http://localhost:8085
  sleuth:
    sampler:
      percentage: 1.0   
