eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/

---
spring:
  data:
    mongodb:
      uri: mongodb://localhost:47017/test
      
spring:
  data:
    mongodb:
      uri: mongodb://localhost:47017/test7
 

---
---
# spring:
#   datasource:
#      hikari:
#       jdbc-url: jdbc:h2:~/testdb
    
   

---
spring:
  zipkin:
    base-url: http://localhost:8085
  sleuth:
    sampler:
      percentage: 1.0   
